service: authorization-service

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true

plugins:
    - serverless-dotenv-plugin
    - serverless-webpack

frameworkVersion: '2'
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

functions:
  basicAuthorizer:
    handler: handler/basicAuthorizer.basicAuthorizer

# resources:
#   Resources:
#   Outputs:
#     basicAuthorizerArn:
#       Value:
#         Fn::GetAtt:
#           - BasicAuthorizerLambdaFunction
#           - Arn
